# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a09a942d713909c008505f801eb7e51693c2083172fe71cdc1d96611a23f0e953788664b4b6eaf4569064e8109d8daeda007f8f155100f30f1f64882839205e8

test:
  secret_key_base: 904d337c8c44fcb143efadfaa157cedd0a201a156a3c42680df8501647430a868e65f71a25417d7a40b7d078ec398ca4d40a084e15ab8233949074ad301b24f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
